### ISSUE TITLE
Simpler way to separate enqueue from register?

### ISSUE THREAD

**Issue by mbaumgartl** [inpsyde/assets#1]
Hi!

I'm trying to switch my plugins to oop style. For better testability I want to stay away from WordPress as much as possible. Without knowing of this Composer package, I started to implement my own asset management abstraction (mostly inspired by https://github.com/schlessera/as-speaking). Now I'm trying to use this package.

In my plugin I want to implement a basic meta box:

```php
<?php

declare(strict_types=1);

namespace Plugin\Metabox;

use RegisterableInterface;
use Renderer\RendererInterface;
use Inpsyde\Assets\{Asset, AssetManager, Handler\ScriptHandler, Script};
use Throwable;

final class Github implements RegisterableInterface
{
    private const ID = 'gh-metabox';
    private const JS_HANDLE = 'gh-metabox';

    /** @var RendererInterface */
    private $renderer;

    /** @var AssetManager */
    private $assetManager;

    public function __construct(
        RendererInterface $renderer,
        AssetManager $assetManager
    ) {
        $this->renderer = $renderer;
        $this->assetManager = $assetManager;
    }

    public function register(): void
    {
        $pluginName = plugin_basename(dirname(__DIR__, 2));
        $url = plugins_url() . '/' . $pluginName . '/assets/js/gh.js';

        $script = new Script(self::JS_HANDLE, $url, Asset::BACKEND, ['enqueue' => false]);
        $script->withLocalize('foo', 'bar');
        $this->assetManager->register($script);

        add_action('add_meta_boxes', function () {
            add_meta_box(
                self::ID,
                'Github',
                [$this, 'process']
            );
        });
    }

    public function process(): void
    {
        /** @var Script $script */
        $script = $this->assetManager->asset(self::JS_HANDLE, Script::class);
        if ($script) {
            $script->canEnqueue(true);
            $scriptHandler = $this->assetManager->handlers()[ScriptHandler::class];
            $scriptHandler->enqueue($script);
        }

        try {
            echo $this->renderer->render('gh-metabox');
        } catch (Throwable $e) {
            echo sprintf('<pre>%s</pre>', $e->getMessage());
        }
    }
}
```
`register` method is called in `add_action('init', ....)`. The reason I do it this way: I want the JavaScript only loaded when the meta box is rendered.

My question: can assets be enqueued in a simpler way than in the code above?

**Comment by Chrico** [comment]
Howdy!

Thanks for your feedback and the really good question! :)

First of all, you can pass a callback to `Asset::canEnqueue()`, which means you can do e.G.:

```php
<?php
$metaboxScript = (new Script('handle', 'script.js', Asset::BACKEND))
        ->inFooter()
        ->canEnqueue(function(){
                // detect the current screen e.G. "post edit/add"
                return true; // or false
         })
        ->withLocalize('foo', 'bar');
```

But this will probably not help you in first place - expect you know the right value to check with `get_current_screen()`.

---

_We're facing following "problem":_ The action from `Asset::HOOK_BACKEND` (`admin_enqueue_scripts`) is running before your render callback from `add_meta_box` is triggered via `do_meta_box`. 

This is probably the reason, why you've injected the `AssetManager` into `Github`-Metabox. to access the `ScriptHandler` and enqueue the `Script`.

What i can - for now - suggest, would be a bit "nicer looking" solution (which does the same as your code): You can just call `wp_enqueue_script` with the handle name in your Metabox-callback. ;-)

This way WordPress will fetch the Script "again" in Footer when printing scripts lately.:

```php

use Inpsyde\Assets\Asset;
use Inpsyde\Assets\AssetManager;
use Inpsyde\Assets\Script;

const GITHUB_METABOX_SCRIPT = 'github-metabox-script';

add_action('plugins_loaded', function(){

    add_action(AssetManager::ACTION_SETUP, function(AssetManager $assetManager) {
        $metaboxScript = new Script(GITHUB_METABOX_SCRIPT, 'script.js', Asset::BACKEND);
        $metaboxScript->inFooter();
        $metaboxScript->canEnqueue(false);
        $metaboxScript->withLocalize('foo', 'bar');

        $assetManager->register($metaboxScript);
    });

    add_action('add_meta_boxes', function () {
        add_meta_box(
            'some-id',
            'Github',
            [new GithubMetaBox(), 'render']
        );
    });
});

final class GithubMetaBox {

    /* snip */

    public function render(): void
    {
        wp_enqueue_script(GITHUB_METABOX_SCRIPT);

        echo "foo";
    }
}
```

---

In future this is probably a good reason to remove single "bootstrap"-entrypoint providing a more robust architecture with the possiblity to use additionally a PSR-11 Container to access the whole API.

**Comment by mbaumgartl** [comment]
Thanks for the quick and detailed response! :+1: 

> This is probably the reason, why you've injected the AssetManager into Github-Metabox. to access the ScriptHandler and enqueue the Script.

I tried to simplify the example as much as possible - maybe a bit too much :wink: My code is more complex: 

My meta box has a dependency to a repository. This repository fetches data from an external API. This data is needed to render the meta box. Because the box listens to custom events, the data also needs to be localized with the script. 

The calls to the repository will be cached in production of course, but I tried to keep things simple and want to query external data sources only once. Maybe I can refactor my code to handle data fetching and script registering outside of the meta box.

> What i can - for now - suggest, would be a bit "nicer looking" solution (which does the same as your code): You can just call wp_enqueue_script with the handle name in your Metabox-callback. ;-)

Thanks for reminding me to keep things simple! :+1: 

> In future this is probably a good reason to remove single "bootstrap"-entrypoint providing a more robust architecture with the possiblity to use additionally a PSR-11 Container to access the whole API.

I'm already using a DI container. But I don't get the benefit. Can you explain it to me, please?

**Comment by Chrico** [comment]
Howdy,

sry for the late response. :-)

> I'm already using a DI container. But I don't get the benefit. Can you explain it to me, please?

Currently we only have 1 single entry point for the pugin which is the `AssetManager::ACTION_SETUP`, where you have to build on top everything. This is may not good, since you need to hook into various hooks in WordPress and the need to access the `AssetManger` or a loader could be earlier / later then this hook.
