### ISSUE TITLE
Register assets using other hooks like "acf/input/admin_enqueue_scripts"

### ISSUE THREAD

**Issue by wolfgangschaefer** [inpsyde/assets#17]
Hi!

When working with other plugins, some suggest to use own hooks to enqueue assets. [ACF for example](https://www.advancedcustomfields.com/resources/acf-input-admin_enqueue_scripts/) suggests using `acf/input/admin_enqueue_scripts`. In case of ACF it uses `admin_enqueue_scripts` with priority `20` to register its assets. After it is done it triggers `acf/input/admin_enqueue_scripts`. 

Is it possible to register assets using other hooks with this library?

**Comment by Chrico** [comment]
Howdy!

Thanks for your question. The `inpsyde/assets` is de-coupled from any Plugin/Theme/Library. It just builds on top of the existing WordPress Core API and allows you to manage Assets (Scripts and Styles) in a more object oriented way. 

I'm not so sure why you should use the API of an Plugin to just register and enqueue Assets. That's maybe a topic related to the Plugin i cannot answer. :) 
What you always can do is either use plain WordPress or `inpsyde/assets` and just add [dependencies](https://github.com/inpsyde/assets/blob/master/docs/03%20-%20Assets.md#dependencies-resolving) to your Assets to enqueue your Assets _after_ the ones from the Plugin.

**Comment by wolfgangschaefer** [comment]
Hi @Chrico 

You are right, dependencies should solve the issue I am having the correct way. I will try that.

Thanks for your input!
