### ISSUE TITLE
2.4.2: could Asset constructor return its instance for easier operation chaining?

### ISSUE THREAD

**Issue by lkraav** [inpsyde/assets#21]
**Describe the bug**
Instead of creating temporary variables with `$script = new Script()`, could I

```php
$assetManager->register(
  new Script( 'foo', 'bar.js' )
    ->inFooter()
    ->...
);
```

Wasn't sure if bug or feature, or I am missing something obvious.

**Comment by Chrico** [comment]
Hey @lkraav 

not sure if i unterstand it correctly :) Following is the same:

```php
$assetManager->register(
  (new Script( 'foo', 'bar.js' ))->inFooter()
);

// same as

$script = (new Script( 'foo', 'bar.js' ))->inFooter();
$assetManager->register($script);

// same as

$script = new Script( 'foo', 'bar.js' );
$script->inFooter();
$assetManager->register($script);
```

i just splitted for the sake of "overview" everything up into a variable to have not so much nesting in documentation. :) 

Every method which sets/adds a value returns `$this`, so you can chain everything to configure your Asset.

**Comment by lkraav** [comment]
Ahh, I missed parenthesis for `(new)`, my bad!
