### ISSUE TITLE
AttributesOutputFilter::removeRootElement() regex requires multi-line compatibility

### ISSUE THREAD

**Issue by lkraav** [inpsyde/assets#22]
**Describe the bug**
With a multi-line inline script attached to an enqueue script handle, I'm hitting this Fatal, traceback https://sentry.io/share/issue/025c3d73635244208dd86f21e3c0006b/

Solved with adding `~...~s` modifier to `$regex`.

**To Reproduce**
Input `$html` is:

```html
<root><script src="cxl-ui.bundled.js?ver=1615493663" id="cxl-ui-js" type="module"></script>
<script id="cxl-ui-js-after">
            ((el) => {
                customElements.whenDefined(el).then(() => {
                    el = document.querySelector(el);

                    /**
                     * Populate context menu.
                     *
                     * @see https://vaadin.com/components/vaadin-context-menu/html-examples/context-menu-items-demos
                     */
                    el.contextMenuItems = window.CXL.contextMenuItems;

                    /**
                     * Headroom.
                     *
                     * @see https://github.com/WickyNilliams/headroom.js
                     */
                    window.CXL.headroom = new Headroom(el, {
                        tolerance: {
                          up: 30,
                          down: 30
                        },
                        onPin: () => {
                            const wpAdminBarEl = document.getElementById('wpadminbar');

                            if (wpAdminBarEl) {
                                el.style.top = `\${wpAdminBarEl.offsetHeight}px`;
                            }
                        }
                    });
                    window.CXL.headroom.init();
                });
            })('cxl-marketing-nav');
</script>
</root>
```

**Expected behavior**
Regex to succeed.

**Additional context**
Are we sure we even need these custom root element wraps?

Other than the above, `withAttributes()` works nicely for `type="module"`:

```php
            $asset_manager->register( $script
                ->enableAutodiscoverVersion()
                ->isInFooter()
                ->withAttributes( [
                    'type' => 'module',
                ] )
            );
```

**Comment by lkraav** [comment]
I was going to write a failing test for it for a PR, but you can probably do it a lot faster @Chrico

**Comment by Chrico** [comment]
Nice catch! Thanks :)

> Are we sure we even need these custom root element wraps?

Yes, because `DOMDocument` needs a root element. Thats okay when you just have `<script src=".."></script>` but when you have inline before/after, then you'll have no root-element and instead multiple ones, which will not work. :) 

----

The problem should be fixed with https://github.com/inpsyde/assets/commit/c2a66d46ba5fcd228e43eb6f99ebdaa8245a2652 - also included some UnitTests to have various combinations of with/without before/after single and/or multiline script. :-)

**Comment by lkraav** [comment]
> The problem should be fixed with c2a66d4 - also included some UnitTests to have various combinations of with/without before/after single and/or multiline script. :-)

Yep, I definitely would not have been able to come up with such a test set.

**Comment by Chrico** [comment]
> Yep, I definitely would not have been able to come up with such a test set.

Neither i. I just came up through your issue! :) New test cases or scenarios are always welcome. It's hard to catch all possibilities in WP, because there's so much possible...

If you're okay with the fix, then i'm going to close that issue.

**Comment by lkraav** [comment]
I think it works now.
