### ISSUE TITLE
Version 2.5 introduced some backward incompatible changes in config handling

### ISSUE THREAD

**Issue by dnaber-de** [inpsyde/assets#26]
A configuration array like this will work in version 2.4 but will fail in version 2.5:

```php
[
    'handle' => 'acme-script',
    'type' => Script::class,
    'url' => "assets/script.js",
    'version' => time(),
    'localize' => function (): array {
        return [];
    },
    'translation' => [
        'domain' => 'acme',
        'path' => '/i18n',
    ],
];
```

The first issue is that the `version` parameter is now passed directly to `BaseAsset::withVersion(string $version);` so it has to be a string. Also `translation` will be passed to `Script::withTranslation(string $domain, string $path);` but in a inappropriate manner. Finally support for `localize` has been removed so there should be a documentation that shows how to refactor packages that depends on inpsyde/assets.

I'm working on a PR

**Comment by retrorism** [comment]
As mentioned by @dnaber-de, there currently is no documentation to help developers make the switch from the `localize` configuration option to `inline: [before][after]`.
When looking into this, I stumbled upon a missing `Script::withInlineScripts` method, which would need to be invoked when using an array configuration.

To make sure that developers can still properly migrate away from `localize` without having to completely refactor their code, we will need (something like) this in the `AssetFactory` class:
```PHP
$propertiesToMethod = [
            'filePath' => 'withFilePath',
            'version' => 'withVersion',
            'dependencies' => 'withDependencies',
            'location' => 'forLocation',
            'enqueue' => 'canEnqueue',
            'handler' => 'useHandler',
            'condition' => 'withCondition',
            'attributes' => 'withAttributes',
            'inline' => 'withInlineScripts', // <-- Add me please :) 
        ];
```
... with a corresponding method in the `Script` class:

```PHP
/**
     * @param array $inline
     *
     * @return static
     *
     * @see https://codex.wordpress.org/Function_Reference/wp_add_inline_script
     */
    public function withInlineScripts(array $inline): Script
    {
        if (!$this->inlineScripts) {
            $this->inlineScripts = [];
        }
        // Sanitization - not really necessary since other keys will be ignored.
        $inline = array_filter(
            $inline,
            static function($key) {
                return in_array($key,['before','after'],true);
            },ARRAY_FILTER_USE_KEY
        );
        $this->inlineScripts = array_merge_recursive($this->inlineScripts, $inline);
        return $this;
    } 
```
This way, the '$asset->inlineScripts` property is properly set when using the ArrayLoader.

**Comment by Chrico** [comment]
@retrorism 
thanks for your input.

There are already 2 methods: `Script::prependInlineScript(string $jsCode): Script` and `Script::appendInlineScript(string $jsCode): Script`, so there is no need to implement a third method which does basically the same, just introduces more complexity... :) With your implementation you'll also introduce some possible bugs like:

```
[
   'inline' => [
      'before' => ['foo'],
      'after' => new stdClass()
   ]
];
```

The before/after have to be a string and you probably also can should be able to add multiple ones via array notation like this:

```
[
   'inline' => [
      'before' => [
            'var foo = "foo"',
            'var bar = "bar",
      ],
      'after' => 'var baz = "baz"
   ]
];
```

Currently i'm waiting for @dnaber-de - he wanted to provide some code/pull request for this. After that i can continue adding/improving things. :)

**Comment by dnaber-de** [comment]
> There are already 2 methods: Script::prependInlineScript(string $jsCode): Script and Script::appendInlineScript(string $jsCode): Script

So instead of adding a new method `Script::withInlineScripts` we could map the config array 
```
[
   'inline' => [
      'before' => [123.456],
      'after' => new stdClass()
   ]
];
```
To the according methods `Script::prependInlineScript()` and `Script::appendInlineScript()`, right? The AssetFactory should check that the config array matches expected type string and throw an exception if not. It works like this for other parameters so why not for `inline`?

**Comment by retrorism** [comment]
Hi @Chrico thanks for the quick feedback. I also considered leveraging those existing prepend - and append methods in my helper function (not sure if this is what @dnaber-de is suggesting). The reason I wanted to add this, is that there is currently no mechanism in place that processes the configuration example you just provided when going the following route for asset generation (say, in a theme):
```PHP
$assets = (new PhpFileLoader())->load(get_template_directory().'/resources/assets.php');
```

Basically I can add the `inline` key-value pair to the return array all I want, but nothing happens in the AssetFactory because the key is not mapped to a method, which seems inconsistent considering that  'withInlineStyles' _is_ a thing:
https://github.com/inpsyde/assets/blob/ff63f34c63ca9dd378c3ea1225b58cdc9f9a7848/src/AssetFactory.php#L93

The current test for inline scripts does not cover a scenario (makes sense of course): https://github.com/inpsyde/assets/blob/ff63f34c63ca9dd378c3ea1225b58cdc9f9a7848/tests/phpunit/Unit/Asset/ScriptTest.php#L157-L176

Or am I missing something?

**Comment by Chrico** [comment]
> To the according methods Script::prependInlineScript() and Script::appendInlineScript(), right? The AssetFactory should check that the config array matches expected type string and throw an exception if not. It works like this for other parameters so why not for inline?

I just dont want to introduce a new public method to the `Script`-class at this point which increases complexity. The `Script`-class has already too many methods - because of WordPress. So we shouldn't just add a new Method because an array-notation could allow something.

> The reason I wanted to add this, is that there is currently no mechanism in place that processes t ...

The `PhpFileLoader` uses the `AssetFactory` internally. So in `AssetFactory`  you would basically just have:

```php
$before = (array)($config['inline']['before'] ??  []);
array_map([$asset, 'appendInlineScript'], $before]);

$after = (array)($config['inline']['after'] ??  []);
array_map([$asset, 'prependInlineScript'], $after]);
```

**Comment by retrorism** [comment]
@Chrico turns out I was working with 2.5.0, so I somehow missed that you already added the necessary handling for inline scripts 😬 sorry for making this thread longer than necessary! 
@dnaber-de is going to prepare the feature branch for a PR from here on.

**Comment by Chrico** [comment]
Pull Request #27 was merged. I'm going to release today a bugfix release. 👍 Thanks for your work.
