### ISSUE TITLE
Access to Webpack-loaded assets by handle

### ISSUE THREAD

**Issue by shvlv** [inpsyde/assets#28]
**Is your feature request related to a problem? Please describe.**
I use `EncoreEntrypointsLoader` following https://github.com/inpsyde/assets/blob/master/docs/02%20-%20Loaders.md#webpackloaders. This lets me avoid a lot of bootstrap code. But in some cases, I need to adjust the default assets configuration. For example, add script localization or en queueing condition. For now, it is possible only to retrieve `Asset` instance by numeric index. The result is some fragile implementation.

```json
{
  "entrypoints": {
    "js/my-cool-js": {
      "js": [
        "../js/my-cool-js.js"
      ]
    }
  }
}
```

```php
$loader = new EncoreEntrypointsLoader();
/**
* @var array<\Inpsyde\Assets\Script> $assets
*/
$assets = $loader->load($this->entrypoint());
$assets[0]->withLocalize(...);
```

**Describe the solution you'd like**
Suggestion is returning from `AbstractWebpackLoader::load` method handle-indexed array. So we can use next:

```php
$assets['js/my-cool-js']->withLocalize(...);
```
The handle is a more reliable key than a numeric index that easily changed with new assets.

**Comment by Chrico** [comment]
The problem with the entrypoints file is, that you can split CSS/JS into multiple files. So it could look like following:

```
{
  "entrypoints": {
    "js/my-cool-js": {
      "js": [
        "../js/my-cool-js-1.js",
        "../js/my-cool-js-2.js",
        "../js/my-cool-js-3.js"
      ]
    }
  }
}
```

So we cannot use they key as handle, because we would overwrite then 1 and 2 with 3.

**Comment by shvlv** [comment]
I see anyway all files have a unique handle - https://github.com/inpsyde/assets/blob/master/src/Loader/EncoreEntrypointsLoader.php#L61, isn't it?

**Comment by Chrico** [comment]
Yes, kind of, but still can cause collisions because CSS and JS are having the same handle as you can see here: https://github.com/inpsyde/assets/blob/master/src/Loader/EncoreEntrypointsLoader.php#L37

So it can look like following:

```
{
  "entrypoints": {
    "js/my-cool-assets": {
      "js": [
        "../js/my-cool-js-1.js",
        "../js/my-cool-js-2.js"
      ],
      "css": [
        "../css/my-cool-.css"
      ],
    }
  }
}
```

Will will produce following handles:

- js/my-cool-assets-1 (script)
- js/my-cool-assets-2 (script)
- js/my-cool-assets-1 (style)

**Comment by shvlv** [comment]
Oh, got it. So we should prepend or append the extension (or asset type) to avoid a collision.
```php
$assets = array_merge($assets, $this->extractAssets($handle . '-script', (array) $files, $directory));
```

**Comment by Chrico** [comment]
Hmm, this would introduce a breaking change. Because what you can (and should) do is:

```json
{
  "entrypoints": {
    "my-handle": {
      "js": [
        "../js/file.js"
      ]
    }
  }
}
```


```php
<?php
use Inpsyde\Assets\AssetManager;
use Inpsyde\Assets\Script;
use Inpsyde\Assets\Asset;
use Inpsyde\Assets\Loader\EncoreEntrypointsLoader;

add_action( 
	AssetManager::ACTION_SETUP, 
	static function(AssetManager $assetManager): void {

		// load assets from entrypoint.json
		$loader = new EncoreEntrypointsLoader();
		$assets = $loader->load($file);

		// register assets
		$assetManager->register(...$assets);

		// access the Script with "my-handle" as name.
		$assetManager
			->asset('my-handle', Script::class)
			->withLocalize('objectName', 'value');
	}
);
```

---

I'll update the documentation regarding this example. :-)

**Comment by shvlv** [comment]
Yes, exactly :). I did not aware about `\Inpsyde\Assets\AssetManager::asset` method. Probably small downside is iteration over all registered assets. But anyway this is my case. Thanks.

**Comment by Chrico** [comment]
In worst case yes, it's iterating over all assets because we do not "restrict" assets to have a unique handle. That's something which has WordPress to take care of.
