### ISSUE TITLE
Unable to remove version

### ISSUE THREAD

**Issue by nlemoine** [inpsyde/assets#3]
Hi! 

Thanks for this awesome library, this is an amazing work.

I'm having trouble removing version of my assets. To be more specific, it seems like you can't remove the query string from the asset URL whatever loader you use (`?ver=something`).

I'm using a `json_manifest` to enqueue my assets in production. The whole point of the `json_manifest` is to cache bust assets without the need to append a query string. 

I think this line is to blame : https://github.com/inpsyde/assets/blob/master/src/BaseAsset.php#L113

[The only way to remove the version query parameter is to set `version` to `null`](https://developer.wordpress.org/reference/classes/WP_Dependencies/add/#parameters), which is currently impossible because the version is always casted to `string`.

**Comment by Chrico** [comment]
Howdy!

thanks for your positive feedback, i'm happy to hear, that the package is used. :-)

I've created a new branch here https://github.com/inpsyde/assets/tree/3_asset_version_nullable so you may can test it out. By default the `Inpsyde\Assets\BaseAsset` will now have `'version' => null,` [1] and also implement the new `Inpsyde\Assets\Asset::version()`-method which allows `?string` [2] as return type.

I'll also do some further updates (till i got feedback from you) to move from Travis to Github Actions and also adding our Inpsyde Coding Standards in version 1.x

----

[1] https://github.com/inpsyde/assets/blob/3_asset_version_nullable/src/BaseAsset.php#L42

[2] https://github.com/inpsyde/assets/blob/3_asset_version_nullable/src/Asset.php#L89

**Comment by nlemoine** [comment]
Thanks for the fast feedback @Chrico!

I just gave a quick shot to the new branch, looks good to me 👍   I only tested in my use case but  from what I've seen, it seems to resolve the main issue.

**Comment by Chrico** [comment]
The pull request was merged and there's a 2.2 release done with the latest change. https://github.com/inpsyde/assets/releases/tag/2.2 

Thanks a lot for your quick feedback! :-)

**Comment by nlemoine** [comment]
Great news! Thanks! 👏

**Comment by Chrico** [comment]
sry to come back to you @nlemoine , but what i figured out is, that if you now use the manifest, the version is still "autodiscovered" based on the filetime by default. That's why i extended the Loaders by also supporting the configuration for this. You can now do following:

```php
<?php

use Inpsyde\Assets\Loader\WebpackManifestLoader;

$loader = new WebpackManifestLoader();
$loader->disableAutodiscoverVersion();

/** @var \Inpsyde\Assets\Asset[] $assets */
$assets = $loader->load('manifest.json');
```

So also here: https://github.com/inpsyde/assets/blob/master/docs/02%20-%20Loaders.md#configure-autodiscovering-version

**Comment by nlemoine** [comment]
Thanks for that update. I'm not using the `WebpackManifestLoader` loader. I handle my assets with the `symfony/asset` component and used `$asset->disableAutodiscoverVersion()` to disable `version`. However, IMHO, I think `autoDiscoverVersion` should be disabled by default with the `WebpackManifestLoader`.

**Comment by Chrico** [comment]
Thanks for your feedback! :) It really depends...we're using Symfony Webpack Encore and not `Encore.enableVersioning()` :-) So it is 50/50 if this should be enabled or disabled by default. 😄

**Comment by nlemoine** [comment]
You're using the `manifest.json` to only get a list of assets to load? Although there's no official standard on this, using `manifest.json` or similar [is meant to cache bust assets](https://symfony.com/doc/current/frontend/encore/versioning.html#loading-assets-from-entrypoints-json-manifest-json) to me. So it's more 60/40 😉

But this is perfectly fine, thanks again for your time and work!
