### ISSUE TITLE
Have `/login` using `wp-rename-login` plugin, and scripts / assets are not enqueued.

### ISSUE THREAD

**Issue by saas786** [inpsyde/assets#48]
When `wp-rename-login` is deactivated, and login page is accessed using `/wp-login.php`, relevant scripts / assets load fine.

Ref:

- https://github.com/inpsyde/assets/blob/51e564ba1fd42f128ee02ddf39da6a77924bc97b/src/Util/AssetHookResolver.php#L80
- https://github.com/inpsyde/wp-context/blob/1e30337f9c43e0d4c3b882a6ff76fff108ea2520/src/WpContext.php#L139

**Comment by Chrico** [comment]
This is to me more a "problem" of `inpsyde/wp-context`, but overall the library is only using the WordPress function `is_login()` or checking the `wp_login_url()`. I created a Pull Request on `inspyde/wp-context` to fix the function name to have proper support with WP 6.1. But overall, the `wp-rename-login` needs to make proper usage of the WP Core functions and  needs to hook into the `wp_login_url()`-function `login_url`-filter to change the login URL to make it work. 👍🏻

**Comment by Chrico** [comment]
This was fixed with latest `inpsyde/wp-context` v1.5.0 - see also here: https://github.com/inpsyde/wp-context/releases/tag/1.5.0
