### ISSUE TITLE
Filter in inline script

### ISSUE THREAD

**Issue by nlemoine** [inpsyde/assets#6]
Hi!

The filters are applied to the inline `script` tags. 

Take the following example:

```php
$testee = new Script('handle', 'foo.js');
$testee->appendInlineScript('var foo = "bar"');
$testee->useDeferFilter();
```

Will output: 
```html
<script defer src='foo.js' id='handle'></script>
<script defer id="handle">
var foo = "bar"
</script>
```

Could you prevent filters to be applied on inline scripts tags?

**Comment by Chrico** [comment]
Commented in Pull-Request #7

**Comment by Chrico** [comment]
This will be solved with the latest implementation of `AttributesOutputFilter`. :)
