### ISSUE TITLE
Improve bootstrap.php

### ISSUE THREAD

**Issue by gmazzap** [inpsyde/assets#9]
In recent WP versions, the file [`plugin.php` has not external dependencies](https://github.com/WordPress/WordPress/blob/master/wp-includes/plugin.php#L17).

This was done to ensure that a file that is executed _before_ WordPress is loaded, can requite the file and start adding actions and filters before WordPress loads.

Thanks to that, we could change [bootstrap.php](https://github.com/inpsyde/assets/blob/master/inc/bootstrap.php) to include this fiel in the case `add_action` is not defined yet.

The current approach can be kept as very last resort fallback, but in theory should never used.

**Comment by gmazzap** [comment]
To be honest, in next major version we should consider to avoid adding hooks at all in files that are loaded from Composer autoload.

**Comment by Chrico** [comment]
This was implemented via #10 and is already released. Close. :)
